### PR TITLE
update block producer configs (warp sync)

### PR DESCRIPTION
**Pull request by eshaben**
### Description

add warp sync flag and reorder the commands

### Checklist

- [ ] I have added a label to this PR 🏷️
- [ ] I have run my changes through Grammarly
- [ ] If this page requires a disclaimer, I have added one
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

### CODE REVIEW

**Review by augustocollado — APPROVED** [review]
LGTM!

**Comment by eshaben** [comment]
@augustocollado added another fix to this PR, can you please review again

**Review by augustocollado — APPROVED** [review]
LGTM

**Review by albertov19 — APPROVED** [review]
LGTM!

**Pull request merged**
