### PR TITLE
Organize the structure of the snippets and images

### PR DESCRIPTION
**Pull request by eshaben**
### Description

This PR organizes the snippets and images to match the structure of the docs.

### Checklist

- [x] I have added a label to this PR 🏷️

### CODE REVIEW

**Review by albertov19 — COMMENTED** [review]
@eshaben is there a way to check if this compiles correctly without checking file by file? The normal compiler does not show an error if the snippet does not exist.

**Comment by eshaben** [comment]
> @eshaben is there a way to check if this compiles correctly without checking file by file? The normal compiler does not show an error if the snippet does not exist.

No, I don't think there is. I did check file-by-file before submitting the PR though, and all of the snippets render as they should.

**Review by albertov19 — APPROVED** [review]
LGTM - Did not check things 1 by 1, just a few random ones

**Review by augustocollado — APPROVED** [review]
Looks good to me

**Pull request merged**
