### PR TITLE
general fixes

### PR DESCRIPTION
**Pull request by eshaben**
### Description

This PR fixes:

- a 404 link
- a broken image (from png > webp conversion)
- meta-refresh redirects -- update links to the new pages instead of the old page and having to do a redirect
- duplicate titles
- general formatting: clean up extra line breaks, additional spacing at end of sentences, table formatting

### Checklist

- [x] I have added a label to this PR 🏷️

### CODE REVIEW

**Review by albertov19 — DISMISSED** [review]
LGTM!

**Comment by eshaben** [comment]
sorry! had to resolve some merge conflicts

**Review by augustocollado — APPROVED** [review]
LGTM! -> There are still some conflicts tho :(

**Review by albertov19 — DISMISSED** [review]
LGTM!

**Review by albertov19 — APPROVED** [review]
LGTM!

**Pull request merged**
