### PR TITLE
Relocate Proxy from Onboarding to Operational Tasks

### PR DESCRIPTION
**Pull request by themacexpert**
### Description

Relocate Proxy Page from Onboarding to Operational Tasks In Block Producers section

### Checklist

- [x] I have added a label to this PR 🏷️
- [ ] I have run my changes through Grammarly
- [ ] If this page requires a disclaimer, I have added one
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

### CODE REVIEW

**Review by eshaben — COMMENTED** [review]
Why is this being relocated?

**Review by eshaben — COMMENTED** [review]
@themacexpert earlier this week I submitted a PR to move all the images for proxy account page (I don't think there were any snippets, but if there were, those were moved too) into the onboarding directory as they were still under operational tasks from the initial placement of this page. So can you please move everything back and make sure it is  all in the right spot? 😆

Also this will require a redirect, so can you please open a PR for the mkdocs repo?

Can you also make sure that we are linking to the moved proxy page from the account setup page?

**Comment by themacexpert** [comment]
> @themacexpert earlier this week I submitted a PR to move all the images for proxy account page (I don't think there were any snippets, but if there were, those were moved too) into the onboarding directory as they were still under operational tasks from the initial placement of this page. So can you please move everything back and make sure it is all in the right spot? 😆
> 
> Also this will require a redirect, so can you please open a PR for the mkdocs repo?
> 
> Can you also make sure that we are linking to the moved proxy page from the account setup page?

added! https://github.com/papermoonio/tanssi-mkdocs/pull/31

**Review by eshaben — APPROVED** [review]
LGTM

**Pull request merged**
